spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sample
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: sample

server:
  port: 8080

logging:
  level:
    org:
      springframework: INFO